### ISSUE TITLE
Cannot make px4fmu on solo-rebase branch

### ISSUE THREAD

**Issue by truhoang** [3drobotics/PX4Firmware-solo#18]
Is the PX4 firmware still being supported? I am trying to flash my Solo pixhawk with the files from master but documentation shows that it doesn't support the pixhawk 2 so I tried the solo-rebase branch but ran into the error

```
~/src/modules/uavcan: No CMakeLists.txt file in the directory
```

If this is no longer supported, is there another PX4 firmware rep for the Solo that I could use? Any help would be appreciated.

**Comment by proficnc** [comment]
Solo firmware is supported directly in ardupilot and open solo.
